apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Lq8T4J43cLf+7LBi,iv:YekKvWgyWT0j6ORBXApa+o+I+B+3ZZqjQSDZftisOAY=,tag:sD934bTFIg6VHNZP12Y0/g==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:UBBfIgb+p14PTMdc,iv:U04YnFgLq2rasx6QfwKg1R9qpQuXTc0Szk8XrfbVZu4=,tag:stkBAE4CmHmdPbyojiKpkw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNjJ0a3RIdDJkSDA2dDM3
            ZjdQSGRGVExrKzA0Z2d4SXlacmlxLzc0TW5VCjZoY3cyOWZIOXozOGMzK25BWWc3
            UmdQSlRIdjFjVHlkbjljM3JJZTNCK1UKLS0tIG8vSTRXMTVYSHBzcTZKSWdLemg2
            bU1ZbEY3WEtWaUNnaTU3aytmMGUzeWMK1kHFTZxJXgecNm/iQgcaruu1tvBdy5Hw
            OQEjV5tT4UP09JSHpuKHJU8tjlQYyrJcw+Sk2PD69aovwr0kukulJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wqgxde8ydcz2cv53vzaaqqpzrl8y6k8ec6aluzfgecau0wq3jemsnm5snw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T10:43:32Z"
    mac: ENC[AES256_GCM,data:CUJVR/nvfBFRNm0/VjbUf59nH/8kmAXD9mLNarm5hZ9gNKlTmUi3kLPRzCc/K7hhta1585jNM8Ixm5nKmGyEWE+PYscSd60fAkFOtJjTVS71UeC24ZbVFwwwh+KQcxSXxV1KkUTdNIWMhs9rAJs2xTqV0vmQIDxFBwm24SHlz44=,iv:Mj+IKKY5x+9Wyqm2mMawBCZEqSccLheKPuDR1wLHuJI=,tag:T5CcEZxzPmrKxTs7WEm92g==,type:str]
    version: 3.13.3
