apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie-expose
  name: mealie-expose
  namespace: mealie
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mealie-expose
  type: LoadBalancer

