apiVersion: v1
kind: Secret
metadata:
    name: audiobookshelf-container-env
sops:
    age:
        - recipient: age1w79tyd0rwrehyd9xwqqpxevqr9jycuhttk6nynlljnmxkl0ztuyqdzh4mz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR29vZ1B3YkpLR1RMckdI
            MFJnODcwWFYzRGJRbVRYMVVDV3F3cnZldVVJCmZ5L3lLNXlxQmFvcjFlSCt5MDlZ
            S0RqbExGd1J6T3lmdDNGd3d1aW5kV00KLS0tIEdSRUl3SStMYWhsZjkrUXo5T1Q3
            TjBKZmVXNEExV1Y0QjRhSzNSeEFBVkkKVItBLOzV1tP+xZogbUDUaLNMl9eEXgHz
            6fnJgjsOkQdZ7BHVMtWr7C+VcCfGh18albtq1mOlITqv+VfriUYPdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T23:00:59Z"
    mac: ENC[AES256_GCM,data:Wc9SfURi07HuTYoCH1GinfljErlkWrHNO3KcigU5nyng3f3MJOBa4NEOa3A+vyoNKI2UbbRN71RvHNQAjU80/LheLSx/TPTJFWGzZ44aJdpacIyIMfHW/9z+S7GObf580ffaUR3uBm6Fk/TPBqujJo3yIpvt4trglcWJkOiGAeo=,iv:9Zq5Vx27MhpwGOAXI69cXzHbu6rgy+HeCEr6EHj8jhc=,tag:fiQFMvDB6sIr4hQ9rR/9/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
