apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ZG/Y2CNsF/KmbwsWQu4bqLzY2uF7K/RU1Hd+ra3eOCkBDlhcW9LmI3ddJPOfWx9l27hv12hjoYIwPDND+tLNAjTbZWvMRNQMFBLXq822pdTkcbz8dXdANFqpquo2pilYkFv6Xzltb6JTMcI5P5dhzjj0A6UNtrnS/M2P0BY9siZxsFQVtiyiS0avzRpvLjiJyrbxUAnosK7bC0PohaarvtqV1BdCJDBRe/xHO5l1r6kpReKbDOKrKPiOO2Hi9qPFz+nUmXMpKLC5hNRNlUXSYf/ZRs/cFbhW9k2GnjpHV668BtgSnteZujeu4e0=,iv:0x+ZW57aKEBGR2b4VQiX0oMOmv1EwjpIR16ZQ2V5pQw=,tag:3CkGLxPTydzNmmR52jbkNg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1w79tyd0rwrehyd9xwqqpxevqr9jycuhttk6nynlljnmxkl0ztuyqdzh4mz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3U2VvVFVUTGNhLzNPYWlM
            VjBoVUhrYVdrZ3ZpdkJqZ08rU1pSb21scFdVCkFpaWJIa2dLRGNiRDZnbS9YRHQy
            YUExcnJ4ZVRBYklzM0NrclFQcUEyaHcKLS0tIFYwUmJpN3ZiUkFKdi84WHdRZ3lq
            cjU5RGJKR0JzbjJPRTZLV0VOZzhpcGcKm2rq4FOJhc+l/E8K6uLivQKwyZGI0lOu
            duYAyI+EWm2I/nh9IKEF1fBVO9GNMJPR0RPAieDUPbRZsGxctJR84A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T22:29:24Z"
    mac: ENC[AES256_GCM,data:ZvkDy3Qb7rEQU4CMjGxkUoXdCXGAfJFFmzwGUpDmtTczi4Z+KJK717EM+LFUbSt6QfzQgg3/QeN/o38g7eErO6dtfLa6L2DZhc5BDFo6yO7F7hj+7Sbpa63HnS4oGvVsAxgUrJC5qwUANh5WnPOVASeltXzuqJSDHE/AJlzSZ8w=,iv:HJY0mTVjj95RjrK7Oe50dlaVFcN+OLfoHHkJ61w0uiE=,tag:m58wdb8r2X6ZsOj7JoNxxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
