apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Fz+Ii1l/sKQ=,iv:pFDiL89U8aOZ/B3srjIGigOifL2w4HL2di1HLZOYjZs=,tag:6G/8P1U9WtXtdk+1b5nqVQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:0aLfOTOdZUZVW5HC,iv:qwpdcvxXQz35GlvNEiG5LqntIqAjYwQ4zZ/IibJ2BVg=,tag:4+FsGHWmyhJjK6O58LnoDg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1w79tyd0rwrehyd9xwqqpxevqr9jycuhttk6nynlljnmxkl0ztuyqdzh4mz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb3QwbWNHcU54MkRCSHdn
            Y2ZXMkxXWERTeUU3MHZGQ0VlRUNlVmJIb3p3CmRQN0ttVEt4Yi9UMUxzMkV4WEV6
            NVNGSGREcTc4U0ZPbnFzTlBTODF5eEkKLS0tIG03VmFEcmNIVThYQk5EWVZ2VDlO
            M05IeU8yNFRPT0g3VGNLMDE5V0pvbUkK7nf8TlFW/vAOLyXumtiCZbPP37uRELs7
            MJGlgLiIxL3WfesEQhp9bEvSSpt1UrM1BphBbx/LUKxub7e51CzoiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T16:32:50Z"
    mac: ENC[AES256_GCM,data:+lMy6aGvWQrPFu+2OAa5kZ6ig0G9hjyn35h/4R4NLaTUBFl6xkeuKIrGhW/ZvRXVKOYi/kVAV3rGzDnX4QA8Wf36DLI4vwKSgwijyxelnzvfit6B0cWY8gjeJkSZnvte8+gt2nkwGyQgfteOY7NGkl/XmrGqloEa5NzduNf5unA=,iv:/F54HfWCtEEey+KEJ5rG9L5mczx6m0sAs+1rg4KKOcA=,tag:QOffNDnSK2eV3jhqk3KcmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
