apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:xNOb20qV+oNQoFPnvjBW0bDrDKNevDAhNZnRC6yfmS+E7qWO95o8Iatz5iG2J3gLZXC3cvQtrfht1n+DQ5fjSVzk+ehVE3qXJWa+oZcQssnDcI//DSwv1IwXlxqqQ4hviq7DHd5oJkThimlmLsOympUssagaC3M6BzESOYtyrMrGJLYBNU1Qx5lDaXNmMXErsKOo/Gwu2x5NfAiTZnr+0gX4g8rEsZXAvQBTa+PtMBmcoGMnWATpT0z8ZsrFaQoIrq7/35IkQdl7H4+ZIHSY50O6ezmMOCn4NHdzx77yOWaHrUq9yP0bktsw9qU=,iv:fD/EX5dX64jDHD/eTNhcAmKwi3jl7Fn0Yl9uS2HKDFY=,tag:5pOHEQDZxJziJipjXV5b2w==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1w79tyd0rwrehyd9xwqqpxevqr9jycuhttk6nynlljnmxkl0ztuyqdzh4mz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORjlESFNXZTVMWEdSTHRq
            M0dLM1pwQ0tWbkNJdk10eWx0RXRrSThpSkRRCjlnT2tMWHh0bFVvU2VzVEN0U0JV
            UEVFSmpjMDJvYUI3c01Cd1BvZ2lSTkUKLS0tIEtqNWNsRERuNEtZK0QrWWIydXJn
            VTl3M1BUU1hSNktsNllDV21rNVA4bjgKw4FF/ezEfzLA37KMnZwYM2cV0kqrAigM
            z82zUgjnGlEs7GHF1dL/p55ir6rOzIOyHgde2ndi0cCaUfEyR9gVRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T15:47:06Z"
    mac: ENC[AES256_GCM,data:Z1YeTL2VWrxUDFIBSny1LJL9o+F3Tze9KSn4PUa3oKV1Q4oF2P3eCybIe/wjmdGzEVksGRjYCHA2hkaxOiHeErFWNlSAOCv2u+HLZPFBwhl+H24EAl7+Lbr0DOeoSPYrRju0n9xfq48f7oeJFmV5RC2sTRIxDwlPwp8uBdvtFHM=,iv:l574P+un4W1ldk+HhBbefmT0JP+vwHcOUr5FNWUZ4k0=,tag:WWy5h+af3jst14gdBJUdbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
