apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:NY4dAcPkX7Hulyrc4Uclxuwl729cigh9G6lSVQoTAgJgrPjTn3dd3rxQrB3dDV6sO+4ap5NCIxZjvpGYFBUuLrhSKemyiEENnI4/oxjcHGTUNDiIAiL2aauagqq19LwwofA02sLWdk0TUqvAHDyRScPXMfzdrxVPezKesdQdsh6jGZPlgBzft642LQVHsX426rADa9X/dPbVbNU71XcVRQQMj9s/h4fF025jyTpW6iHNJGdTzs+MODjFCzSsl38nyFsKrUk3wzosWtBQCm9118kEPcPjssdjCAQ2JXHxF9wvP7SBFzZfqpTDM9c=,iv:RBQrA1UfYOUHyoDDigEmc88oo0Ww2XhbXDaenqDpSds=,tag:njlIIkM+J38EGw2FeL54LQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1w79tyd0rwrehyd9xwqqpxevqr9jycuhttk6nynlljnmxkl0ztuyqdzh4mz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyY0hzYlhjZTU4RXN6VHA2
            ZjdoUTVhVVJCZlFLVHpqUFpNNC9XNlJwNndjCk1zNVgydEU3ck1oY05CaktUMEV3
            czdBZTFGTHhYUGo0MjRtcWlrZkJTcG8KLS0tIEtxeW9UbGZBZzZpeEtWYkZxWFlF
            cVpBLy9ONS9QbCtQZ1RHaUloRGZDaWcKl2VnIaPsd8mX1g/4sALkylW8S8XyTNd5
            0Jp+6iiyWIqFxUR/L54nue30JN0YwtfKva1q8aZ8pXtXJwGKbm32mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T20:51:55Z"
    mac: ENC[AES256_GCM,data:qfKtIOd51y9mhQriegNwqtQaeSWMZCGm/VB1KMjqdoQRXGLWVFw/1VWv82QS+QDFHweW60CAvmpAU3qy4VlaJgSiJbKV1qUNHs17otMyQuTbbSeGwLux/YLF9nDR7PlDGLJMCsLyqvTP92z+0KaOLhCHs9McTno/yqJnn4CWFYA=,iv:11Mxh2/RiqOlesSXLSdYOGZ8nZfD3xLB+TyVPTxg5mg=,tag:AqZ5o5YvoHGejPsu0dQ5Wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
