apiVersion: v1
kind: Service
metadata:
  labels:
    app: openwebui-expose
  name: openwebui-expose
  namespace: openwebui
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 8080
  selector:
    app: openwebui-expose
  type: LoadBalancer

