apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:rZ/lwmqlRGuqB4AFKSMpBIXMfJuWdjISuIDz4c7f+cydBNvlpOMj45fWIXJnzaByG9uYfHMUKX4=,iv:0+8Awn3MtdEm4gftCh26hLTAlnOaaMUR4FGZkTIVHP0=,tag:C5kGCwZU8JZviIJmrJA9ug==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1w79tyd0rwrehyd9xwqqpxevqr9jycuhttk6nynlljnmxkl0ztuyqdzh4mz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWGpWcGtUMXI4Z3NUN010
            TFBTam9HbHUwb2haWmJMRUNJSllTZTd3QVRJClBKdHBuZWNGWTl0aGNDdVZnN3VV
            OEluakVRRlNRRURIcE9GdE83TGkxNzQKLS0tIFV3VTMwQ1VCbkdpdXY0NWFRK09U
            aEhtUVF3eElBL1E2eFgwVUpncHRUQTQK5/TMRSlqd03pJqyZLMDeZP9nYVFZfcd4
            rZkehbBVGWVMVOQmYd09aZ0ofUqCYgE4RMKaikR8SheKMKmf6uKApw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T20:54:39Z"
    mac: ENC[AES256_GCM,data:O3p8ADwOPDa/wGO+M+/lCLiS0PRHQgGfhBxUkL/B/ccz1zfyU585U6P1aXidY+H4uB4e8v6QG3RiFvoj9JT8cSFql07dIriwZdJ0PdjtN+qzXcK5P/v6GUiBGxwdbkO8N4fKqffNmMEgQKiBBq53gdIcRMWbSRYSP21HT9kGPYk=,iv:Vf1vzhhQqp7jZas1tCesqca8oH1sl4KPd7wIfOteIG4=,tag:qIzFMbhT+TxM/dG3iQ6lTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
